name: Test
on:
    workflow_dispatch:


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: battila7/get-version-action@v2
                id: get_version
            -   run: echo ${{ steps.get_version.outputs.version }}
            -   run: echo ${{ steps.get_version.outputs.version-without-v }}
            -   run: echo ${{ steps.get_version.outputs.prerelease }}
